### ISSUE TITLE
Unable to build Windows version from source

### ISSUE THREAD

**Issue by jakobkg** [Readek/Melee-Stream-Tool#8]
Hi! in this repo, in the "Stream Tool" directory, there's a .exe file for the Stream Tool. How was this built?
The provided Windows build method (electron-forge make) does not generate a single .exe file but a whole folder of things, mostly Electron specific stuff, and building this and moving it into the "Stream Tool" folder still does not work as the file paths in the code are all hard coded to be relative paths from the "Interface Source Code" folder to the "Stream Tool" folder.
In my fork I have made the paths dynamic based on an environment variable and this works fine for tile Linux AppImage, but I'm still unable to recreate or make a replacement for the single .exe in the "Stream Tool" folder.
Could you please provide build steps to recreate or replace the .exe file? Thanks!

**Comment by Readek** [comment]
Ah yes, building the exe is not intuitive, at all. This repo was done when I was learning Electron and because of it, many things are not done right. It is way easier to do this on more recent versions of the Stream Tool ([for example](https://github.com/Readek/RoA-Stream-Tool/wiki/7.-Customizing-the-GUI#building-a-new-executable)), but this one is stuck in the past.

If I remember correctly, you first need to change the paths of `gui.js` inside of the `Interface Source Code` folder. For portable exes to work, it needs an special variable. For example (only use one set):

```javascript
//change to these paths when building the executable
//Linux (appimage)
const mainPath = path.resolve('.', 'Resources', 'Texts');
const charPath = path.resolve('.', 'Resources', 'Characters'); */
//Windows (if building a portable exe)
const mainPath = path.resolve(process.env.PORTABLE_EXECUTABLE_DIR, 'Resources', 'Texts');
const charPath = path.resolve(process.env.PORTABLE_EXECUTABLE_DIR, 'Resources', 'Characters');
```

Then, to build the exe, electron-forge is not actually being used here, instead i used [electron.build](https://www.electron.build/). The json provided on this repo is a complete mess, so its probably a better idea to make your own.


If i ever end up coding a new Melee ST version, this gui situation is the first thing that I will fix.

**Comment by jakobkg** [comment]
Thank you! `process.env.PORTABLE_EXECUTABLE_DIR` was the magic word I was looking for, I'll be able to get the rest working from here :D

**Comment by jakobkg** [comment]
For the record, this way of determining the path will work both when working on the source and when running an executable placed in the Stream Tool directory. I added a dependency on `dotenv` for the environment variable, but that can probably be replaced with a more clever launch script in `package.json`. This works for developing, Linux AppImages and portable Windows executables!

gui.js:

```
const rootPath = process.env.DEV_ENV ? path.join(__dirname, '..', '..', 'Stream Tool')
                  : process.platform == 'win32' ? process.env.PORTABLE_EXECUTABLE_DIR
                    : path.dirname(process.env.APPIMAGE);
const textPath = path.join(rootPath, 'Resources', 'Texts');
const charPath = path.join(rootPath, 'Resources', 'Characters');
```

**Comment by Readek** [comment]
Good solution! Newer stream tool versions also check for operating system, but are decoupled from the dev enviroment issues since it all runs without one, it just checks for the path given by node. Adding this feature to the Melee ST would cost some time tho, maybe some day.
