### ISSUE TITLE
Player names don't appear on the scoreboard after updating OBS to version 28

### ISSUE THREAD

**Issue by Sukid** [Readek/Melee-Stream-Tool#9]
Player names won't appear on the scoreboard after installing OBS 28.0.1. I've tried re-adding the scoreboard html to the scene, I've made sure to check the refresh when inactive and custom framerate options. I've also refreshed the cache. The caster names and round names show up fine. I also tried changing the character border color and no dice there either. :(
 It can sometimes also take a moment to fully finish loading while the score ticks bounce around, but that also happened in previous versions.

**Comment by Readek** [comment]
In fact, the full Scoreboard is 100% broken on OBS 28, thanks for letting me know. This isnt the first time OBS's browser updates break something...

At the moment I have no idea what is going on. VS Screen works fine, but SC doesn't and I'm not sure what the difference is. Everything works fine in an actual browser. I tried to open up OBS's remote web console, but the thing doesn't throw any errors.

**Comment by Readek** [comment]
The cause is, somehow, the resize text function which enters an infinite loop, specifically when its called on players. And apparently, removing the height condition while keeping the width condition fixes this without altering the text's appearance. I committed the fix, could you try it out and confirm this fixes the problem?

**Comment by Sukid** [comment]
POGNIFICENT it popped right up! Came up faster than it did even before the obs update too.
